"""
AUTO GENERATED FILE.
DO NOT EDIT MANUALLY.
"""

ROLE_METADATA = {'.NET Developer': {'candidate_count': 2788,
                    'core_skills': ['Spark',
                                    'Go',
                                    'Databricks',
                                    'Django',
                                    'Microservices',
                                    'Accounting',
                                    'Scrum',
                                    'Illustrator',
                                    'Excel',
                                    'Docker',
                                    'Snowflake',
                                    'SAP',
                                    'Sales',
                                    'Next.js',
                                    'Tally']},
 'AI Engineer': {'candidate_count': 21,
                 'core_skills': ['BM25',
                                 'Diffusion Models',
                                 'QLoRA',
                                 'Embeddings',
                                 'Sentence Transformers',
                                 'Recommendation Systems',
                                 'RAG',
                                 'scikit-learn',
                                 'LangChain',
                                 'NLP',
                                 'Feature Engineering',
                                 'Vector Search',
                                 'FAISS',
                                 'Qdrant',
                                 'Hugging Face Transformers']},
 'AI Research Engineer': {'candidate_count': 153,
                          'core_skills': ['Diffusion Models',
                                          'Forecasting',
                                          'GANs',
                                          'BentoML',
                                          'Computer Vision',
                                          'Time Series',
                                          'Kubeflow',
                                          'CNN',
                                          'Feature Engineering',
                                          'Weights & Biases',
                                          'OpenCV',
                                          'MLOps',
                                          'MLflow',
                                          'TTS',
                                          'Data Science']},
 'AI Specialist': {'candidate_count': 130,
                   'core_skills': ['OpenCV',
                                   'ASR',
                                   'YOLO',
                                   'MLOps',
                                   'Time Series',
                                   'GANs',
                                   'Speech Recognition',
                                   'MLflow',
                                   'Image Classification',
                                   'Diffusion Models',
                                   'Object Detection',
                                   'Feature Engineering',
                                   'BentoML',
                                   'Data Science',
                                   'Computer Vision']},
 'Accountant': {'candidate_count': 5764,
                'core_skills': ['Rust',
                                'Databricks',
                                'CSS',
                                'HTML',
                                'Node.js',
                                'Tailwind',
                                'Apache Flink',
                                'Hadoop',
                                'Flask',
                                'Webpack',
                                'Apache Beam',
                                'Redis',
                                'AWS',
                                'Docker',
                                'Excel']},
 'Analytics Engineer': {'candidate_count': 764,
                        'core_skills': ['MLOps',
                                        'Weights & Biases',
                                        'Feature Engineering',
                                        'TTS',
                                        'CNN',
                                        'Kubeflow',
                                        'Object Detection',
                                        'Statistical Modeling',
                                        'Data Science',
                                        'ASR',
                                        'Speech Recognition',
                                        'GANs',
                                        'YOLO',
                                        'Forecasting',
                                        'BentoML']},
 'Applied ML Engineer': {'candidate_count': 23,
                         'core_skills': ['Kubeflow',
                                         'Sentence Transformers',
                                         'NLP',
                                         'Weaviate',
                                         'Pinecone',
                                         'LoRA',
                                         'Vector Search',
                                         'PyTorch',
                                         'ASR',
                                         'LlamaIndex',
                                         'pgvector',
                                         'OpenSearch',
                                         'Learning to Rank',
                                         'Prompt Engineering',
                                         'LangChain']},
 'Backend Engineer': {'candidate_count': 704,
                      'core_skills': ['Object Detection',
                                      'Forecasting',
                                      'MLflow',
                                      'Weights & Biases',
                                      'Diffusion Models',
                                      'OpenCV',
                                      'TTS',
                                      'Kubeflow',
                                      'BentoML',
                                      'Computer Vision',
                                      'YOLO',
                                      'GANs',
                                      'Time Series',
                                      'MLOps',
                                      'Reinforcement Learning']},
 'Business Analyst': {'candidate_count': 5833,
                      'core_skills': ['ETL',
                                      'Scrum',
                                      'Salesforce CRM',
                                      'PowerPoint',
                                      'Terraform',
                                      'Rust',
                                      'Next.js',
                                      'Sales',
                                      'SQL',
                                      'Django',
                                      'Redis',
                                      'Vue.js',
                                      'Excel',
                                      'Node.js',
                                      'gRPC']},
 'Civil Engineer': {'candidate_count': 5702,
                    'core_skills': ['Illustrator',
                                    'Kubernetes',
                                    'PostgreSQL',
                                    'Salesforce CRM',
                                    'Project Management',
                                    'CI/CD',
                                    'HTML',
                                    'PowerPoint',
                                    'Spring Boot',
                                    'Node.js',
                                    'Hadoop',
                                    'Scrum',
                                    'Accounting',
                                    'Agile',
                                    'Snowflake']},
 'Cloud Engineer': {'candidate_count': 2836,
                    'core_skills': ['Airflow',
                                    'React',
                                    'CSS',
                                    'Spark',
                                    'Flask',
                                    'Figma',
                                    'Project Management',
                                    'GraphQL',
                                    'Accounting',
                                    'Content Writing',
                                    'JavaScript',
                                    'Java',
                                    'Azure',
                                    'Apache Flink',
                                    'Agile']},
 'Computer Vision Engineer': {'candidate_count': 132,
                              'core_skills': ['Object Detection',
                                              'Time Series',
                                              'Data Science',
                                              'CNN',
                                              'Weights & Biases',
                                              'MLflow',
                                              'Feature Engineering',
                                              'Computer Vision',
                                              'Diffusion Models',
                                              'TTS',
                                              'Machine Learning',
                                              'GANs',
                                              'Kubeflow',
                                              'BentoML',
                                              'Statistical Modeling']},
 'Content Writer': {'candidate_count': 5727,
                    'core_skills': ['Six Sigma',
                                    'gRPC',
                                    'Redux',
                                    'TypeScript',
                                    'Django',
                                    'ETL',
                                    'Marketing',
                                    'Docker',
                                    'PowerPoint',
                                    'Tally',
                                    'Content Writing',
                                    'Terraform',
                                    'Data Pipelines',
                                    'BigQuery',
                                    'Vue.js']},
 'Customer Support': {'candidate_count': 5750,
                      'core_skills': ['FastAPI',
                                      'Marketing',
                                      'Angular',
                                      'AWS',
                                      'Figma',
                                      'Salesforce CRM',
                                      'Apache Flink',
                                      'Excel',
                                      'Next.js',
                                      'Data Pipelines',
                                      'Docker',
                                      'Tailwind',
                                      'Rust',
                                      'Kubernetes',
                                      'SAP']},
 'Data Analyst': {'candidate_count': 728,
                  'core_skills': ['Kubeflow',
                                  'Image Classification',
                                  'Time Series',
                                  'Reinforcement Learning',
                                  'CNN',
                                  'GANs',
                                  'TTS',
                                  'YOLO',
                                  'Feature Engineering',
                                  'Statistical Modeling',
                                  'Speech Recognition',
                                  'OpenCV',
                                  'Weights & Biases',
                                  'ASR',
                                  'Data Science']},
 'Data Engineer': {'candidate_count': 744,
                   'core_skills': ['ASR',
                                   'Image Classification',
                                   'Forecasting',
                                   'GANs',
                                   'YOLO',
                                   'MLOps',
                                   'Kubeflow',
                                   'Statistical Modeling',
                                   'MLflow',
                                   'Computer Vision',
                                   'Data Science',
                                   'Speech Recognition',
                                   'Object Detection',
                                   'CNN',
                                   'Feature Engineering']},
 'Data Scientist': {'candidate_count': 145,
                    'core_skills': ['MLflow',
                                    'MLOps',
                                    'TTS',
                                    'Image Classification',
                                    'Diffusion Models',
                                    'Computer Vision',
                                    'Feature Engineering',
                                    'Data Science',
                                    'OpenCV',
                                    'Reinforcement Learning',
                                    'Object Detection',
                                    'Weaviate',
                                    'LoRA',
                                    'Qdrant',
                                    'Speech Recognition']},
 'DevOps Engineer': {'candidate_count': 2787,
                     'core_skills': ['Spark',
                                     'Kubernetes',
                                     'GraphQL',
                                     'Illustrator',
                                     'Salesforce CRM',
                                     'Marketing',
                                     'Figma',
                                     'Terraform',
                                     'Airflow',
                                     'Microservices',
                                     'Kafka',
                                     'Agile',
                                     'Tailwind',
                                     'ETL',
                                     'SEO']},
 'Frontend Engineer': {'candidate_count': 2738,
                       'core_skills': ['Vue.js',
                                       'Flask',
                                       'Terraform',
                                       'Six Sigma',
                                       'Marketing',
                                       'HTML',
                                       'gRPC',
                                       'Project Management',
                                       'Redux',
                                       'MongoDB',
                                       'Figma',
                                       'Photoshop',
                                       'Go',
                                       'Agile',
                                       'PowerPoint']},
 'Full Stack Developer': {'candidate_count': 2873,
                          'core_skills': ['BigQuery',
                                          'Databricks',
                                          'CI/CD',
                                          'Terraform',
                                          'Webpack',
                                          'GraphQL',
                                          'Marketing',
                                          'Apache Beam',
                                          'Node.js',
                                          'Docker',
                                          'PostgreSQL',
                                          'Django',
                                          'Sales',
                                          'Airflow',
                                          'Angular']},
 'Graphic Designer': {'candidate_count': 5689,
                      'core_skills': ['Next.js',
                                      'Kubernetes',
                                      'Project Management',
                                      'Sales',
                                      'HTML',
                                      'AWS',
                                      'Angular',
                                      'SAP',
                                      'Figma',
                                      'Apache Beam',
                                      'SEO',
                                      'Rust',
                                      'Docker',
                                      'GraphQL',
                                      'Agile']},
 'HR Manager': {'candidate_count': 5830,
                'core_skills': ['CI/CD',
                                'Vue.js',
                                'React',
                                'Tailwind',
                                'Webpack',
                                'Terraform',
                                'SAP',
                                'BigQuery',
                                'Angular',
                                'Kafka',
                                'Rust',
                                'Figma',
                                'Redux',
                                'Scrum',
                                'Node.js']},
 'Java Developer': {'candidate_count': 2809,
                    'core_skills': ['Databricks',
                                    'REST APIs',
                                    'Excel',
                                    'Apache Flink',
                                    'Six Sigma',
                                    'Content Writing',
                                    'Salesforce CRM',
                                    'TypeScript',
                                    'PostgreSQL',
                                    'Spring Boot',
                                    'Apache Beam',
                                    'Go',
                                    'Figma',
                                    'Java',
                                    'GraphQL']},
 'Junior ML Engineer': {'candidate_count': 131,
                        'core_skills': ['Speech Recognition',
                                        'Time Series',
                                        'MLOps',
                                        'MLflow',
                                        'YOLO',
                                        'Diffusion Models',
                                        'CNN',
                                        'Reinforcement Learning',
                                        'Feature Engineering',
                                        'Weights & Biases',
                                        'Kubeflow',
                                        'Statistical Modeling',
                                        'Data Science',
                                        'OpenCV',
                                        'Computer Vision']},
 'Lead AI Engineer': {'candidate_count': 3,
                      'core_skills': ['Qdrant',
                                      'pgvector',
                                      'Deep Learning',
                                      'Elasticsearch',
                                      'Python',
                                      'Machine Learning',
                                      'NLP',
                                      'Learning to Rank',
                                      'Vector Search',
                                      'scikit-learn',
                                      'Semantic Search',
                                      'Feature Engineering',
                                      'Text Encoders',
                                      'PEFT',
                                      'Spring Boot']},
 'ML Engineer': {'candidate_count': 167,
                 'core_skills': ['Feature Engineering',
                                 'Statistical Modeling',
                                 'OpenCV',
                                 'Object Detection',
                                 'Kubeflow',
                                 'Weights & Biases',
                                 'Computer Vision',
                                 'TTS',
                                 'ASR',
                                 'Image Classification',
                                 'MLOps',
                                 'Time Series',
                                 'CNN',
                                 'Forecasting',
                                 'Data Science']},
 'Machine Learning Engineer': {'candidate_count': 24,
                               'core_skills': ['Elasticsearch',
                                               'PyTorch',
                                               'scikit-learn',
                                               'Fine-tuning LLMs',
                                               'NLP',
                                               'LoRA',
                                               'Qdrant',
                                               'QLoRA',
                                               'Hugging Face Transformers',
                                               'Deep Learning',
                                               'MLflow',
                                               'OpenSearch',
                                               'Machine Learning',
                                               'Recommendation Systems',
                                               'Milvus']},
 'Marketing Manager': {'candidate_count': 5524,
                       'core_skills': ['Flask',
                                       'Microservices',
                                       'Spring Boot',
                                       'SAP',
                                       'Kafka',
                                       'PostgreSQL',
                                       'Databricks',
                                       'Angular',
                                       'Spark',
                                       'gRPC',
                                       'ETL',
                                       'Sales',
                                       'Redux',
                                       'Tailwind',
                                       'SEO']},
 'Mechanical Engineer': {'candidate_count': 5791,
                         'core_skills': ['Docker',
                                         'SQL',
                                         'Figma',
                                         'Accounting',
                                         'Apache Beam',
                                         'Microservices',
                                         'Redux',
                                         'Databricks',
                                         'gRPC',
                                         'Azure',
                                         'Tally',
                                         'dbt',
                                         'Go',
                                         'Airflow',
                                         'Tailwind']},
 'Mobile Developer': {'candidate_count': 2757,
                      'core_skills': ['GraphQL',
                                      'Excel',
                                      'Kubernetes',
                                      'Salesforce CRM',
                                      'REST APIs',
                                      'HTML',
                                      'TypeScript',
                                      'JavaScript',
                                      'Figma',
                                      'Scrum',
                                      'Kafka',
                                      'Docker',
                                      'Rust',
                                      'Angular',
                                      'BigQuery']},
 'NLP Engineer': {'candidate_count': 14,
                  'core_skills': ['OpenSearch',
                                  'Elasticsearch',
                                  'LlamaIndex',
                                  'LangChain',
                                  'BM25',
                                  'QLoRA',
                                  'Semantic Search',
                                  'Weaviate',
                                  'Hugging Face Transformers',
                                  'Prompt Engineering',
                                  'Forecasting',
                                  'scikit-learn',
                                  'Embeddings',
                                  'Learning to Rank',
                                  'Python']},
 'Operations Manager': {'candidate_count': 5744,
                        'core_skills': ['AWS',
                                        'Agile',
                                        'Tally',
                                        'FastAPI',
                                        'dbt',
                                        'Kafka',
                                        'CSS',
                                        'Illustrator',
                                        'Sales',
                                        'Go',
                                        'SEO',
                                        'CI/CD',
                                        'GCP',
                                        'Vue.js',
                                        'Hadoop']},
 'Project Manager': {'candidate_count': 5754,
                     'core_skills': ['Excel',
                                     'Airflow',
                                     'GCP',
                                     'Illustrator',
                                     'Snowflake',
                                     'Agile',
                                     'SQL',
                                     'Databricks',
                                     'CSS',
                                     'Project Management',
                                     'SEO',
                                     'Scrum',
                                     'gRPC',
                                     'Azure',
                                     'HTML']},
 'QA Engineer': {'candidate_count': 2682,
                 'core_skills': ['Apache Beam',
                                 'Airflow',
                                 'Flask',
                                 'Tally',
                                 'ETL',
                                 'JavaScript',
                                 'Terraform',
                                 'SAP',
                                 'Spring Boot',
                                 'CI/CD',
                                 'React',
                                 'Webpack',
                                 'PostgreSQL',
                                 'Go',
                                 'Excel']},
 'Recommendation Systems Engineer': {'candidate_count': 26,
                                     'core_skills': ['Embeddings',
                                                     'FAISS',
                                                     'OpenSearch',
                                                     'Qdrant',
                                                     'Milvus',
                                                     'Pinecone',
                                                     'Machine Learning',
                                                     'Hugging Face Transformers',
                                                     'scikit-learn',
                                                     'Prompt Engineering',
                                                     'PEFT',
                                                     'LoRA',
                                                     'LangChain',
                                                     'Sentence Transformers',
                                                     'Python']},
 'Sales Executive': {'candidate_count': 5713,
                     'core_skills': ['Project Management',
                                     'Apache Beam',
                                     'Redux',
                                     'JavaScript',
                                     'Vue.js',
                                     'FastAPI',
                                     'GCP',
                                     'REST APIs',
                                     'Terraform',
                                     'dbt',
                                     'Django',
                                     'Snowflake',
                                     'PostgreSQL',
                                     'Photoshop',
                                     'Angular']},
 'Search Engineer': {'candidate_count': 23,
                     'core_skills': ['PEFT',
                                     'BM25',
                                     'Hugging Face Transformers',
                                     'Weaviate',
                                     'Semantic Search',
                                     'PyTorch',
                                     'TTS',
                                     'Fine-tuning LLMs',
                                     'LLMs',
                                     'Sentence Transformers',
                                     'Milvus',
                                     'Reinforcement Learning',
                                     'Qdrant',
                                     'MLOps',
                                     'LlamaIndex']},
 'Senior AI Engineer': {'candidate_count': 4,
                        'core_skills': ['Haystack',
                                        'Python',
                                        'scikit-learn',
                                        'Weaviate',
                                        'Sentence Transformers',
                                        'QLoRA',
                                        'NLP',
                                        'Pinecone',
                                        'Recommendation Systems',
                                        'Deep Learning',
                                        'Prompt Engineering',
                                        'Vector Representations',
                                        'Content Matching',
                                        'Feature Engineering',
                                        'Data Science']},
 'Senior Applied Scientist': {'candidate_count': 4,
                              'core_skills': ['TensorFlow',
                                              'Recommendation Systems',
                                              'NLP',
                                              'pgvector',
                                              'Information Retrieval Systems',
                                              'Text Encoders',
                                              'Model Adaptation',
                                              'Machine Learning',
                                              'OpenSearch',
                                              'LoRA',
                                              'PyTorch',
                                              'BM25',
                                              'QLoRA',
                                              'Fine-tuning LLMs',
                                              'Kubeflow']},
 'Senior Data Engineer': {'candidate_count': 687,
                          'core_skills': ['YOLO',
                                          'Computer Vision',
                                          'Diffusion Models',
                                          'OpenCV',
                                          'Forecasting',
                                          'BentoML',
                                          'GANs',
                                          'CNN',
                                          'MLflow',
                                          'Image Classification',
                                          'Object Detection',
                                          'Statistical Modeling',
                                          'MLOps',
                                          'Feature Engineering',
                                          'Reinforcement Learning']},
 'Senior Data Scientist': {'candidate_count': 19,
                           'core_skills': ['Vector Search',
                                           'Qdrant',
                                           'OpenSearch',
                                           'NLP',
                                           'Haystack',
                                           'Recommendation Systems',
                                           'QLoRA',
                                           'Forecasting',
                                           'LlamaIndex',
                                           'RAG',
                                           'Machine Learning',
                                           'Fine-tuning LLMs',
                                           'Semantic Search',
                                           'Image Classification',
                                           'Learning to Rank']},
 'Senior Machine Learning Engineer': {'candidate_count': 6,
                                      'core_skills': ['Information Retrieval',
                                                      'TensorFlow',
                                                      'OpenSearch',
                                                      'Learning to Rank',
                                                      'scikit-learn',
                                                      'LangChain',
                                                      'Machine Learning',
                                                      'LLMs',
                                                      'Haystack',
                                                      'Fine-tuning LLMs',
                                                      'Vector Search',
                                                      'BM25',
                                                      'PyTorch',
                                                      'Pinecone',
                                                      'Deep Learning']},
 'Senior NLP Engineer': {'candidate_count': 6,
                         'core_skills': ['Semantic Search',
                                         'Haystack',
                                         'TensorFlow',
                                         'PEFT',
                                         'Python',
                                         'NLP',
                                         'LoRA',
                                         'pgvector',
                                         'Hugging Face Transformers',
                                         'Image Classification',
                                         'Elasticsearch',
                                         'MLOps',
                                         'Prompt Engineering',
                                         'Information Retrieval',
                                         'Deep Learning']},
 'Senior Software Engineer': {'candidate_count': 653,
                              'core_skills': ['Time Series',
                                              'Diffusion Models',
                                              'CNN',
                                              'Statistical Modeling',
                                              'ASR',
                                              'OpenCV',
                                              'Speech Recognition',
                                              'Reinforcement Learning',
                                              'GANs',
                                              'MLflow',
                                              'Image Classification',
                                              'BentoML',
                                              'Kubeflow',
                                              'Weights & Biases',
                                              'Data Science']},
 'Senior Software Engineer (ML)': {'candidate_count': 142,
                                   'core_skills': ['Image Classification',
                                                   'Speech Recognition',
                                                   'Object Detection',
                                                   'BentoML',
                                                   'YOLO',
                                                   'GANs',
                                                   'Data Science',
                                                   'Reinforcement Learning',
                                                   'MLflow',
                                                   'Weights & Biases',
                                                   'Feature Engineering',
                                                   'Forecasting',
                                                   'Statistical Modeling',
                                                   'Time Series',
                                                   'ASR']},
 'Software Engineer': {'candidate_count': 3450,
                       'core_skills': ['Accounting',
                                       'Six Sigma',
                                       'AWS',
                                       'Project Management',
                                       'Redux',
                                       'Microservices',
                                       'Figma',
                                       'Kafka',
                                       'GraphQL',
                                       'SAP',
                                       'Sales',
                                       'CSS',
                                       'Spark',
                                       'Terraform',
                                       'TypeScript']},
 'Staff Machine Learning Engineer': {'candidate_count': 6,
                                     'core_skills': ['BM25',
                                                     'Deep Learning',
                                                     'QLoRA',
                                                     'Python',
                                                     'Prompt Engineering',
                                                     'Qdrant',
                                                     'OpenSearch',
                                                     'Sentence Transformers',
                                                     'MLOps',
                                                     'pgvector',
                                                     'Feature Engineering',
                                                     'Pinecone',
                                                     'RAG',
                                                     'YOLO',
                                                     'LlamaIndex']}}

ALL_ROLES = ['.NET Developer',
 'AI Engineer',
 'AI Research Engineer',
 'AI Specialist',
 'Accountant',
 'Analytics Engineer',
 'Applied ML Engineer',
 'Backend Engineer',
 'Business Analyst',
 'Civil Engineer',
 'Cloud Engineer',
 'Computer Vision Engineer',
 'Content Writer',
 'Customer Support',
 'Data Analyst',
 'Data Engineer',
 'Data Scientist',
 'DevOps Engineer',
 'Frontend Engineer',
 'Full Stack Developer',
 'Graphic Designer',
 'HR Manager',
 'Java Developer',
 'Junior ML Engineer',
 'Lead AI Engineer',
 'ML Engineer',
 'Machine Learning Engineer',
 'Marketing Manager',
 'Mechanical Engineer',
 'Mobile Developer',
 'NLP Engineer',
 'Operations Manager',
 'Project Manager',
 'QA Engineer',
 'Recommendation Systems Engineer',
 'Sales Executive',
 'Search Engineer',
 'Senior AI Engineer',
 'Senior Applied Scientist',
 'Senior Data Engineer',
 'Senior Data Scientist',
 'Senior Machine Learning Engineer',
 'Senior NLP Engineer',
 'Senior Software Engineer',
 'Senior Software Engineer (ML)',
 'Software Engineer',
 'Staff Machine Learning Engineer']

ALL_SKILLS = ['HTML',
 'Databricks',
 'Redux',
 'Terraform',
 'Angular',
 'Figma',
 'Salesforce CRM',
 'Vue.js',
 'Sales',
 'Accounting',
 'Agile',
 'Kafka',
 'Excel',
 'BigQuery',
 'CI/CD',
 'Project Management',
 'Airflow',
 'AWS',
 'Flask',
 'Scrum',
 'Illustrator',
 'Kubernetes',
 'ETL',
 'CSS',
 'Docker',
 'Next.js',
 'Apache Beam',
 'Java',
 'Go',
 'TypeScript',
 'JavaScript',
 'dbt',
 'REST APIs',
 'Spark',
 'Marketing',
 'Tally',
 'GraphQL',
 'Snowflake',
 'Webpack',
 'Six Sigma',
 'SEO',
 'SAP',
 'GCP',
 'PostgreSQL',
 'Rust',
 'Apache Flink',
 'gRPC',
 'Content Writing',
 'SQL',
 'Hadoop',
 'Redis',
 'Tailwind',
 'Photoshop',
 'FastAPI',
 'Microservices',
 'PowerPoint',
 'Spring Boot',
 'Data Pipelines',
 'Django',
 'MongoDB',
 'Node.js',
 'Azure',
 'React',
 'Hugging Face Transformers',
 'LangChain',
 'Information Retrieval',
 'LLMs',
 'Recommendation Systems',
 'Semantic Search',
 'Sentence Transformers',
 'Embeddings',
 'Vector Search',
 'Prompt Engineering',
 'Pinecone',
 'FAISS',
 'RAG',
 'Fine-tuning LLMs',
 'YOLO',
 'GANs',
 'Feature Engineering',
 'OpenCV',
 'ASR',
 'Image Classification',
 'Computer Vision',
 'Speech Recognition',
 'CNN',
 'Kubeflow',
 'MLOps',
 'BentoML',
 'Data Science',
 'Reinforcement Learning',
 'Object Detection',
 'Diffusion Models',
 'MLflow',
 'Time Series',
 'Weights & Biases',
 'Forecasting',
 'TTS',
 'Statistical Modeling',
 'QLoRA',
 'pgvector',
 'Weaviate',
 'Milvus',
 'Learning to Rank',
 'BM25',
 'TensorFlow',
 'Qdrant',
 'Python',
 'PyTorch',
 'PEFT',
 'LoRA',
 'NLP',
 'Machine Learning',
 'Deep Learning',
 'Haystack',
 'Elasticsearch',
 'LlamaIndex',
 'scikit-learn',
 'OpenSearch',
 'Information Retrieval Systems',
 'Search Backend',
 'Text Encoders',
 'Vector Representations',
 'Content Matching',
 'Model Adaptation',
 'Ranking Systems',
 'Search & Discovery',
 'Workflow Orchestration',
 'Search Infrastructure',
 'Indexing Algorithms',
 'Open-source ML libraries',
 'Natural Language Processing',
 'Document Processing']
